Add celery task scheduler, book request, librarian issue, notifications and waiting list functionality.
djunicode/departmental-library-management-app pull request #19
Opened 2021-03-06 18:29 UTC by shreyasrami

2021-04-13 16:40 UTC, SakshiUppoor requested changes

2021-04-13 16:40 UTC, SakshiUppoor commented on libraryBackend/libraryApp/api.py
> +                        alerted_on=datetime.date.today(),
This line gives the following error `RuntimeWarning: DateTimeField Image.added_on received a naive datetime (2021-04-13 14:48:22) while time zone support is active.`

2021-04-13 16:40 UTC, SakshiUppoor commented on libraryBackend/libraryApp/api.py
> +                return Response(issue.id)
Please return a more meaningful response.

2021-04-13 16:40 UTC, SakshiUppoor commented on libraryBackend/libraryApp/api.py
> +class IssuedViewSet(viewsets.ModelViewSet):
Students and teachers should not have update and delete permissions.

2021-04-13 16:40 UTC, SakshiUppoor commented on README.md
> +```
Add instructions for the celery commands too.

2021-04-13 16:48 UTC, SakshiUppoor commented
Also try making a file to run during setup which will automatically create the periodic task if it doesn't exist already.

2021-04-14 03:02 UTC, SakshiUppoor commented
The code looks good to me. Just one doubt: If a student/teacher have issued a book, they shouldn't be able to issue it again if they haven't returned it, right?

2021-04-14 03:43 UTC, shreyasrami commented
> The code looks good to me. Just one doubt: If a student/teacher has issued a book, they shouldn't be able to issue it again if they haven't returned it, right?

Fixed this.

2021-04-14 04:06 UTC, merged