3 types of user authentication
djunicode/departmental-library-management-app pull request #4
Opened 2021-02-03 05:49 UTC by junaidgirkar

3 user models created: Student, Teacher and Librarian. Registration process available for all 3 and a login page which returns token on user credentials.

2021-02-03 06:01 UTC, SakshiUppoor commented
Please maintain everything in libraryApp only so that file structure remains the same as mentioned in the readme

2021-02-06 03:33 UTC, Harshvartak requested changes

2021-02-06 03:33 UTC, Harshvartak commented on libraryBackend/libraryApp/api.py
> +                "user": UserSerializer(
UserSerializer not defined error thrown for user signup, the user gets registered but no response

2021-02-06 03:33 UTC, Harshvartak commented on libraryBackend/libraryApp/models.py
> +    department = models.CharField(max_length=40)
1. Department Choices to be present
2. SAP validators in the backend
3. SAP as a required field for the Student and Teacher model, Librarian ID for Librarian model, also change blank to False for the mentioned fields

2021-02-06 03:33 UTC, Harshvartak commented on libraryBackend/libraryApp/serializers.py
> +            "department",
Graduation Date Missing

2021-02-06 03:33 UTC, Harshvartak commented on libraryBackend/libraryApp/api.py
> +    return Response({"token": token.key}, status=HTTP_200_OK)
Make the Login Function Swagger Doc Compatible

2021-02-08 17:10 UTC, Harshvartak approved these changes

2021-02-08 17:11 UTC, merged